Bug 32212559: Deployment stuck at ‘in progress’: bug in startup code path
Azure/iot-hub-device-update pull request #22
Opened 2021-03-22 23:17 UTC by shiyi-peng

When the previous action is Download, and then the device lost connection, when it gets connected and starts up again - it is stuck at `at progress` because the agent reports `idle` in this case, while it should resume the Download workflow.

Add the logic to resume Download workflow as Nox suggested. 

Validation to ensure that this won’t regress anything is needed.

2021-03-30 22:28 UTC, nihemstr commented on src/agent/adu_core_interface/src/agent_workflow.c
> +            // There's a pending download requrest.
>requrest [](start = 42, length = 8)

Spelling :)

2021-03-30 22:30 UTC, nihemstr requested changes
:clock1:

2021-04-12 21:51 UTC, nihemstr commented
>     if (IsAducResultCodeFailure(isInstalledResult.ResultCode))

If checking this value covers all possible internal errors then the else{} portion of the logic will not be caught in an infinite loop. Otherwise we'll be stuck trying to download. 

Might need to check that this isn't preventing ADU from reporting potential internall error codes and failures.

---
Refers to: src/agent/adu_core_interface/src/agent_workflow.c:440 in 6ade5c0. [](commit_id = 6ade5c0059972ded19c0a88ff277ea8779b056c2, deletion_comment = False)

2021-05-04 19:45 UTC, Nox-MSFT commented on src/agent/adu_core_interface/src/agent_workflow.c
> +            workflowData->WorkflowId, sizeof(workflowData->WorkflowId) / sizeof(workflowData->WorkflowId[0]));
>sizeof(workflowData->WorkflowId) / sizeof(workflowData->WorkflowId[0]) [](http://example.com/codeflow?start=38&length=70)

You could use ARRAY_SIZE macro here..

e.g. 

ARRAY_SIZE(workflowData->WorkflowId)

2021-05-04 19:48 UTC, Nox-MSFT approved these changes
:shipit:

2021-05-05 01:22 UTC, Nox-MSFT commented on src/agent/adu_core_interface/src/adu_core_export_helpers.c
> +        memset(workflowData->WorkFolder, 0, sizeof(*(workflowData->WorkFolder)));
> memset(workflowData->WorkFolder, 0, sizeof(*(workflowData->WorkFolder))); [](http://example.com/codeflow?start=7&length=74)

Write to NULL address? Segfault?

2021-05-05 01:22 UTC, Nox-MSFT requested changes
:clock1:

2021-05-05 14:52 UTC, Nox-MSFT approved these changes
:shipit:

2021-05-05 16:41 UTC, shiyi-peng commented
>     if (IsAducResultCodeFailure(isInstalledResult.ResultCode))

It is checking (resultCode <= 0); so I think we are covered here?


---
In reply to: [818266782](https://github.com/Azure/iot-hub-device-update/pull/22#issuecomment-818266782) [](ancestors = 818266782)

---
Refers to: src/agent/adu_core_interface/src/agent_workflow.c:440 in 565791b. [](commit_id = 565791b1212d9ea22f1ad20fc6500af8f3fd4629, deletion_comment = False)

2021-05-05 20:57 UTC, nihemstr approved these changes
:shipit:

2021-05-05 20:57 UTC, merged