use custom script in CancelApply and Apply step
Azure/iot-hub-device-update pull request #347
Opened 2023-01-18 15:18 UTC by JoergZeidler

2023-01-19 00:36 UTC, Nox-MSFT requested changes

2023-01-19 10:42 UTC, JoergZeidler commented on src/extensions/step_handlers/swupdate_handler_v2/src/swupdate_handler_v2.cpp
> +        return ADUC_Result{ ADUC_Result_Failure };
done

2023-01-24 14:51 UTC, Nox-MSFT approved these changes

2023-01-24 14:52 UTC, Nox-MSFT commented
@JoergZeidler , think so much for your contribution!

2023-01-24 14:53 UTC, merged