Adu update bash script
Azure/iot-hub-device-update pull request #41
Opened 2021-04-14 19:42 UTC by JeffMill

bash version of the PowerShell script.

Bonus: Split README to PowerShell and bash versions.

Bonus: Fixed up some stuff in the PowerShell README

2021-04-14 21:34 UTC, JeffMill commented on tools/AduCmdlets/README-bash.md
> +./create-adu-import-manifest.sh -p 'Microsoft' -n 'Toaster' -v '2.0' -t 'microsoft/swupdate:1' -i'5' -c Fabrikam,Toaster -c Contoso,Toaster ./file1.json ./file2.zip
>-i'5' [](start = 95, length = 5)

I should make this `i '5'` to be consistent.

2021-04-14 21:39 UTC, JeffMill commented on tools/AduCmdlets/create-adu-import-manifest.sh
> +
checking with Leo, but `date --utc --iso-8601=seconds` might suffice here if ns aren't significant, and .NET DateTime is being used to parse.

2021-04-14 21:40 UTC, JeffMill commented on tools/AduCmdlets/create-adu-import-manifest.sh
> +# Using "jq" would be better, but trying to eliminate script dependencies.
>eliminate [](start = 44, length = 9)

reduce (openssl is a dependency)

2021-04-14 22:33 UTC, devlie requested changes

2021-04-15 00:09 UTC, JeffMill commented on tools/AduCmdlets/README-bash.md
> +Bash script `create-adu-import-manifest.sh` can be used to create an *import manifest* to import an update into Azure Device Update.
yeah, but the powershell script and the folder name still have "adu".  I suppose I can change the MD files for now.

---
In reply to: [613560343](https://github.com/Azure/iot-hub-device-update/pull/41#discussion_r613560343) [](ancestors = 613560343)

2021-04-15 00:10 UTC, JeffMill commented on tools/AduCmdlets/create-adu-import-manifest.sh
> +-p NAME         Update provider name
so remove "name" here?

---
In reply to: [613586257](https://github.com/Azure/iot-hub-device-update/pull/41#discussion_r613586257) [](ancestors = 613586257)

2021-04-15 00:40 UTC, devlie commented on tools/AduCmdlets/create-adu-import-manifest.sh
> +-p NAME         Update provider name
Yeah, 
`-p PROVIDER         Update provider`

2021-04-15 02:17 UTC, dpokluda approved these changes

2021-04-15 16:28 UTC, merged