Ubuntu Core Snap - AzIoTIdentity integration
Azure/iot-hub-device-update pull request #429
Opened 2023-03-17 09:13 UTC by shiyi-peng

Merging to feature/snap

2023-03-17 21:45 UTC, Nox-MSFT approved these changes

2023-03-20 23:44 UTC, nihemstr requested changes
Need justification for the commented out sections

2023-03-20 23:44 UTC, nihemstr commented on src/utils/eis_utils/src/eis_utils.c
> +// EISErr EISIdentitiesFileWriter(uint32_t timeoutMS, const char* filePath)
why are we checking in large blocks of commented out code?

2023-03-20 23:44 UTC, nihemstr commented on src/utils/eis_utils/src/eis_utils.c
> +//     const time_t expirySecsSinceEpoch, uint32_t timeoutMS, ADUC_ConnectionInfo* provisioningInfo)
More commented out code...

2023-03-21 02:33 UTC, nihemstr approved these changes
Approving changes to remove block

2023-03-24 06:26 UTC, merged