add a couple inline comments to ADUC_Safe_StrCopyN
Azure/iot-hub-device-update pull request #587
Opened 2023-12-06 18:27 UTC by jw-msft

2023-12-07 23:16 UTC, JeffMill requested changes

2023-12-07 23:16 UTC, JeffMill commented on src/utils/c_utils/src/string_c_utils.c
> +    // Ensure we don't overflow the destination buffer
nit? parameters are "destByteLen" and "numSrcCharsToCopy".  Chars or Bytes?

2023-12-07 23:16 UTC, JeffMill commented on src/utils/c_utils/src/string_c_utils.c
> +    // Ensure we don't overflow the destination buffer
464: destByteLen better be at least 1 as resultant buffer always has at least a \0

2023-12-13 01:29 UTC, jw-msft commented
closing this one as its been superseded by #588

2023-12-13 01:29 UTC, closed without merging