Fixed bug reporting in progress out of band, re-introducing InProgress workflow step
Azure/iot-hub-device-update pull request #659
Opened 2024-09-26 16:28 UTC by nihemstr

2024-10-03 00:44 UTC, jw-msft requested changes
I am blocking this PR because need to revert the change to line 834 on main.c which was previously fixing the undefined behavior / segfault.

2024-10-03 00:44 UTC, jw-msft commented on src/adu_workflow/src/agent_workflow.c
> +
2 newlines in a row. touch, stage, and run clang-format?

2024-10-03 00:44 UTC, jw-msft commented on src/agent/src/main.c
> +    Log_Warn("Shutdown signal detected: %s", sig);
the fix here seems to be regressing a previous fix. It should be %d to avoid undefined behavior (including segfault)

2024-10-24 19:41 UTC, jw-msft commented on src/agent/src/main.c
> +    Log_Warn("Shutdown signal detected: %s", sig);
I've addressed this in https://github.com/Azure/iot-hub-device-update/commit/34e6d5cd2f25934b9370fc351c9532e663b741ca

2024-10-24 19:41 UTC, jw-msft approved these changes

2024-10-24 23:02 UTC, jw-msft approved these changes

2024-11-04 21:10 UTC, Nox-MSFT approved these changes

2024-11-05 05:20 UTC, ortogonal commented
Just for information, I tested this PR and had some issues. See my comment here, https://github.com/Azure/iot-hub-device-update/issues/625#issuecomment-2435455883

2024-11-07 14:39 UTC, RichardHubertPtw commented
Thanks for making some progress here! Please let us know if we can assist with tests or is there an alternative approach in the works? If so, please inform in the original issue ASAP. We are getting desperate :-)

2024-11-07 18:13 UTC, merged